# This is a workflow to compile the cdeps source without cime
name: extbuild
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-cdeps:
    runs-on: ubuntu-latest
    env:
      CC: mpicc
      FC: mpifort
      CXX: mpicxx
      CPPFLAGS: "-I/usr/include -I/usr/local/include"
      # Versions of all dependencies can be updated here
      ESMF_VERSION: ESMF_8_1_1
      PNETCDF_VERSION: pnetcdf-1.12.2
      NETCDF_FORTRAN_VERSION: v4.5.2
      # These should match in number
      PIO_VERSION: pio-2.5.4
      PIO_VERSION_DUMB: pio2_5_4
    steps:
      - id: checkout-CDEPS
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - id: load-env
        run: sudo apt-get install gfortran wget openmpi-bin netcdf-bin libopenmpi-dev libnetcdf-dev
      - id: build-ESMF
        if: steps.cache-esmf.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install gfortran
          sudo apt-get install wget
          sudo apt-get install openmpi-bin libopenmpi-dev
          sudo apt-get install netcdf-bin libnetcdf-dev libnetcdff-dev
          sudo apt-get install pnetcdf-bin libpnetcdf-dev
          sudo apt-get install autotools-dev autoconf
      - name: Cache PARALLELIO
        id: cache-PARALLELIO
        uses: actions/cache@v3
        with:
          path: ${GITHUB_WORKSPACE}/pio
          key: ${{ runner.os }}-${{ env.ParallelIO_VERSION }}-parallelio2
      - name: Build ParallelIO
        if: steps.cache-PARALLELIO.outputs.cache-hit != 'true'
        uses: NCAR/ParallelIO/.github/actions/parallelio_cmake@9390e30e29d4ebbfbef0fc72162cacd9e8f25e4e
        with:
          parallelio_version: ${{ env.ParallelIO_VERSION }}
          enable_fortran: True
          install_prefix: ${GITHUB_WORKSPACE}/pio
      - name: Install ESMF
        uses: esmf-org/install-esmf-action@v1
        env:
          ESMF_COMPILER: gfortran
          ESMF_BOPT: g
          ESMF_COMM: openmpi
          ESMF_NETCDF: nc-config
          ESMF_PNETCDF: pnetcdf-config
          ESMF_INSTALL_PREFIX: ${GITHUB_WORKSPACE}/ESMF
          ESMF_PIO: external
          ESMF_PIO_INCLUDE: ${GITHUB_WORKSPACE}/pio/include
          ESMF_PIO_LIBPATH: ${GITHUB_WORKSPACE}/pio/lib
        with:
          path: ~/pio
          key: ${{ runner.os }}-${{ env.PIO_VERSION }}.pio
          restore-keys: |
            ${{ runner.os }}-${{ env.NETCDF_FORTRAN_VERSION }}-netcdf-fortran
            ${{ runner.os }}-${{ env.PNETCDF_VERSION }}-pnetcdf
      - name: Build PIO
        if: steps.cache-PIO.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/NCAR/ParallelIO/releases/download/${{ env.PIO_VERSION_DUMB }}/${{ env.PIO_VERSION }}.tar.gz
          tar -xzvf ${{ env.PIO_VERSION }}.tar.gz
          mkdir build-pio
          pushd build-pio
          cmake -Wno-dev -DNetCDF_C_LIBRARY=/usr/lib/x86_64-linux-gnu/libnetcdf.so -DNetCDF_C_INCLUDE_DIR=/usr/include -DCMAKE_PREFIX_PATH=/usr -DCMAKE_INSTALL_PREFIX=$HOME/pio -DPIO_HDF5_LOGGING=Off -DPIO_ENABLE_EXAMPLES=Off -DPIO_ENABLE_LOGGING=Off -DPIO_ENABLE_TIMING=Off -DNetCDF_Fortran_PATH=$HOME/netcdf-fortran -DPnetCDF_PATH=$HOME/pnetcdf ../${{ env.PIO_VERSION }}
          make VERBOSE=1
          make install
          popd

      - name: Build CDEPS
        uses: ./.github/actions/buildcdeps
        with:
          esmfmkfile: $ESMFMKFILE
          pio_path: ${GITHUB_WORKSPACE}/pio
          src_root: ${GITHUB_WORKSPACE}
          cmake_flags: " -Wno-dev -DCMAKE_BUILD_TYPE=DEBUG -DWERROR=ON  -DCMAKE_Fortran_FLAGS=\"-DCPRGNU -g -Wall \
          -ffree-form -ffree-line-length-none -fallow-argument-mismatch \""
      - name: Test CDEPS
        run: |
          cd build-cdeps
          make VERBOSE=1
